### ISSUE TITLE
latLng Variables 

### ISSUE THREAD

**Issue by Ethaan** [vazco/meteor-vazco-maps#5]
Hi vazco nice package, but im having a question its there a way to pass Reactive variable into lat and lng variables? im having some issues there

``` javascript
    tmpl.newMap = new tmpl.mapEngine({
        div: '#map-canvas',
        lat: 52.22968,
        lng: 21.01223,
```

its there a way to replace that "static" value with something like **position.coords.latitude** or using the Geolocation package from meteor? 

its there a way to accomplish this? getting current user position and place it on the map?

**Comment by radekmie** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
