### ISSUE TITLE
Google map object is re-created each re-render

### ISSUE THREAD

**Issue by aksonov** [vazco/meteor-vazco-maps#6]
It seems not correct behaviour. Let's image we have hundreds of markers, search box, etc. and user clicked other page and then return back to map - could we avoid full recreation of google.map object?

**Comment by radekmie** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
