### ISSUE TITLE
setIcon on click -> graphic errors on zoom

### ISSUE THREAD

**Issue by Obiwarn** [vazco/meteor-vazco-maps#8]
when I use setIcon to change the icon of my markers on click I get strange graphic errors (clipping, wrong sized icons) when I zoom the webpage (not the map) in the browser . E.g. zoom browser to 200% and then click an icon.

I use svg for the images and CoffeScript:

addMarker
  icon:  '/img/mapMarker.svg'
  click: (e) ->
            this.setIcon('/img/mapMarkerSelected.svg')

**Comment by radekmie** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
